### ISSUE TITLE
[BUG] Download mirror doesn't appear to be available (https://mirror.csclub.uwaterloo.ca/)

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/nifi-formula#17]
### Pillar / config used

---

### Describe the bug

@codeboyQ2n5ha45 While running the weekly tests across formulas, all the test instances were failing:

* https://gitlab.com/myii/nifi-formula/-/pipelines/316663010

Usually, that happens when the previous version of `nifi` is no longer available.  When this has happened, I've sent through a commit to bump the version, such as:

* 5b91eae38cf02a8080449502095cb2ec0b0570b0
* 8f0b47cf91ffdec4ed4542340a9e2e7f64959a38

In this case, we're getting this error instead:

```sls
                 ID: nifi-package-install-pkg-installed
           Function: archive.extracted
               Name: /opt/nifi-1.13.2
             Result: False
            Comment: Error: HTTP 599: Timeout while connecting reading https://mirror.csclub.uwaterloo.ca/apache/nifi/1.13.2/nifi-1.13.2-bin.tar.gz
```

Looks like it's time to change the mirror, probably from https://www.apache.org/dyn/closer.lua?path=/nifi/1.13.2/nifi-1.13.2-bin.tar.gz.  The one issue there is that the mirror list is different based upon one's location.

**Comment by wrender** [comment]
I'll try and take a look at this soon.

**Comment by wrender** [comment]
@myii   Looks like you bumped this to version 14.0 already to fix this issue?

**Comment by myii** [comment]
> @myii Looks like you bumped this to version 14.0 already to fix this issue?

@wrender Not quite.  Let me try to use error codes to explain the situation better.

### `Error: HTTP 404: Not Found reading` (Usual situation)

* This is the error that's triggered when a new version of NiFi needs to be used.
* When this has happened, I visit https://mirror.csclub.uwaterloo.ca/apache/nifi/ to see the next version available.
* I update the two files, push the commit here and all is working again.

### `Error: HTTP 599: Timeout while connecting reading` (Abnormal situation)

* This is the error that is behind this bug report.
* When this took place, https://mirror.csclub.uwaterloo.ca/apache/nifi/ was not available, so it wasn't a version number issue.
* I confirmed that at the time with the URL I shared above: https://www.apache.org/dyn/closer.lua?path=/nifi/1.13.2/nifi-1.13.2-bin.tar.gz.
  - Tested the formula with one of the other mirrors and it was working.
  - So it appeared that this particular mirror had disappeared.
  - Hence, the request for selecting a more reliable mirror.

To be fair, the mirror only disappeared this one time (on June 8th) -- but the tests are only generally run once a week.  In any case, it's worth noting that the mirror has had a problem, in case we ever encounter the `599` again.

### Maintenance issue

I probably should mention this in a separate issue but the breakdown above is relevant:

* The weekly testing is done across around 100 formulas.
* This formula is the only one that requires regular intervention whenever a new version is released upstream.
  - Meaning, it's higher maintenance than the other formulas.
* So I have a few questions about how we could deal with this:
  - Do you know of any mirrors that keep an archive of the older versions of Nifi, so this doesn't have to be updated so often?
  - Or do any of the mirrors provide a URL to the `latest` or `current`, so we could use that instead of a specific version?
  - Worst case, how about we upload a particular version somewhere and adapt the CI to download from there instead?  This would only affect the CI, not the formula itself, which would still download from the given mirror.

**Comment by wrender** [comment]
Yep..looks like they have an archive here: 
 https://archive.apache.org/dist/nifi/

**Comment by myii** [comment]
> Yep..looks like they have an archive here:
> https://archive.apache.org/dist/nifi/

@wrender Thanks, when I get a chance, I'll update the CI here to use the archive instead, by using a separate test pillar based on `pillar.example`.
